name: Build and Release JBUnityAnalyzerTool

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./JBUnityAnalyzerTool/JBUnityAnalyzerTool.csproj

    - name: Build project
      run: dotnet build ./JBUnityAnalyzerTool/JBUnityAnalyzerTool.csproj -c Release --no-restore

    - name: Publish self-contained EXE
      run: dotnet publish ./JBUnityAnalyzerTool/JBUnityAnalyzerTool.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true

    - name: Upload publish folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: JBUnityAnalyzerTool
        path: ./JBUnityAnalyzerTool/bin/Release/net9.0/win-x64/publish/

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload EXE to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./JBUnityAnalyzerTool/bin/Release/net9.0/win-x64/publish/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
